### ISSUE TITLE
Questions regarding your write-up

### ISSUE THREAD

**Issue by s-pic** [mooyoul/timeout-experiments#1]
Hi @mooyoul ,

I came across your efforts to fix timeout behaviour in axios. Thank you for putting all this together.

I am currently building an httpClient for a browser-based app that basically wraps axios
and - since I am writing test for various edge cases - came across timeout related problems tracked in https://github.com/axios/axios/issues/647 and https://github.com/axios/axios/issues/2710.

I gotta say I am still a bit confused an I hope it is fine for you if I ask you here 
for your expertise about the topic. Here are my questions:

### 1. How can I interpret the Call timeout?

You are writing 
> "Call Timeout" indicates that "complete" HTTP call didn't completed in specified time.
It includes entire timings from DNS Lookup to Response body download.

Does this mean the Call timeout is the broadest type of a timeout, meaning that is (in contrast
to more specific timeout types like read timeout) does not state during what request phase the
error ouccured?

### 2. Does the xhr adapter handle all sort of timeout cases if the `timeout` option is used?
Your are writing that the XHR Adapter only handles a Call Timeout.
In relation to Question 1 -- does this mean if I use the timeout request option for an xhr-based 
request, all kind of network-related error sources (no connection established,
slow responses/requests, DNS lookup failure) are handled by axios?

I am a little confused here because I am reading different things about axios behaves.
https://github.com/axios/axios/issues/647 reads like axios does not handle connect timeouts _in general_,
not just in Node.
But when I run an axios request to a non-routable URL in a [codesandbox](https://codesandbox.io/s/axios-forked-26inc), the timeout option leads to the connect timeout being handled as error.

Am I seeing this correct: I only need workarounds like [using a cancel token](https://github.com/axios/axios/issues/647#issuecomment-322209906) if I want to handle connect timeouts in NodeJS. In the browser, using the `timeout `option is sufficient.

**Comment by mooyoul** [comment]
Hello @s-pic , Thank you for your interest. You've found the right place to ask. Welcome! 👋 

> 1. How can I interpret the Call timeout?
> You are writing
>
> "Call Timeout" indicates that "complete" HTTP call didn't completed in specified time.
> It includes entire timings from DNS Lookup to Response body download.
> 
> Does this mean the Call timeout is the broadest type of a timeout, meaning that is (in contrast
to more specific timeout types like read timeout) does not state during what request phase the
error ouccured?

Yes. Call Timeout limits entire timeframe.
Setting Call Timeout limits sum of (DNS Query Time + Socket Assign / Connect time + (Optional - SSL initial handshake time) + HTTP Request writing time + HTTP Response receiving time).

Please refer to below docs:
- https://github.com/sindresorhus/got#timeout - Timeout explanation of `got` package.
- https://www.baeldung.com/okhttp-timeouts -  Timeout explanation of `okhttp` package. It is a great write-up about various timeouts even if this document is talking about`okhttp`, which is Java library. 


> 2. Does the xhr adapter handle all sort of timeout cases if the timeout option is used?
> Your are writing that the XHR Adapter only handles a Call Timeout.
> In relation to Question 1 -- does this mean if I use the timeout request option for an xhr-based
> request, all kind of network-related error sources (no connection established,
> slow responses/requests, DNS lookup failure) are handled by axios?

Normally timeout of XHR defines "Call Timeout". but it may vary to depending on Browser implementation of XHR timeout. There's no clear way to know what happened during network call - especially timeout related.
For example, If there was DNS Lookup failure, It will be reported with "Network Error" message via "error" event of XHR. but you won't be able to know exact root cause of error. Even if detailed timings or error information can be inspected through Network Inspector of Devtools, Unfortunately, there are no clear error information in XHR.

> I am a little confused here because I am reading different things about axios behaves.
> axios/axios#647 reads like axios does not handle connect timeouts in general,
> not just in Node.
> But when I run an axios request to a non-routable URL in a codesandbox, the timeout option leads to the connect timeout being handled as error.

Be aware, Sending XHR request to non-routable address usually fails due to CORS issue. Unfortunately, There are no easy way to sending request to non-routable destination.

> Am I seeing this correct: I only need workarounds like using a cancel token if I want to handle connect timeouts in NodeJS. In the browser, using the timeout option is sufficient.

Yes. You're correct. You can rely on `timeout` option of XHR, but you won't be able to set advanced timeout limits.

In my opinion, Timeout handling in axios is currently "partially broken". Browser seems ok, but Node isn't.
I highly recommend to you to use alternative if possible.
If you are targeting to Node.js runtime, `got` package of sindresorhus is decent choice.

**Comment by s-pic** [comment]
He @mooyoul ,

Thanks so much for getting back to me and for taking the time to answer my questions. I am happy, closing this ;)
